# environment.yml
# conda env update --name sweep --file D:\XXXIIIGGG\projects\pySweep\pySweepWS\environment.yml --prune

name: sweep

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12.13
  - pip
  - nidaqmx-python
  - numpy
  - scipy
  - scipy-stubs
  - matplotlib
  - sympy
  - pyvista
  - pandas
  - pydantic
  - ruff
  - pre-commit
  - pytest
  - pytest-cov
  - commitizen

  - pip:
    - mph
    - -e ./src
